Fix "TypeError: require(...).listen is not a function" on index.js:6 "require('socket.io').listen(server)" while starting server (managing dependency versions)